### PR TITLE
Add viscoplastic material with Norton rule

### PR DESCRIPTION
**Pull request by ovainola**
Adding material with a given interface. Material can be tested
using simulator, see tests/test_viscoplastic folder.

### CODE REVIEW

**Comment by ahojukka5** [comment]
Could you paste figure of stress-strain curve here?

**Comment by ovainola** [comment]
my bad, seems that I forgot to add unittest file to commit, amending.

**Comment by ahojukka5** [comment]
You could do uniaxial example, like with other materials, see this: https://github.com/JuliaFEM/Materials.jl/blob/master/examples/one_element_ideal_plastic.jl

**Comment by TeroFrondelius** [comment]
@ovainola how difficult it was to adapt this refactored way of working? Would you describe it easy?

**Comment by ovainola** [comment]
@TeroFrondelius quite easy, I fancy that this "plugin style" implementation is quite easy to grasp

**Comment by ovainola** [comment]
image

stress - strain curves with different dt values. plot script in test/test_viscoplastic/plot_material.jl

**Comment by ahojukka5** [comment]
Hmm what about the Jacobian?

**Pull request merged**
